apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  proxy.conf: |
    #Return 404 if no server name matches
    #server {
    #listen 80 default_server;
    #    server_name "";
    #    return 503 "No server is currently configured for the requested host.";
    #}
    #server {
    #listen 80 default_server;
    #  location / {
    #    access_log off;
    #    return 503 "NOOOOOOOOOOO\n";
    #  }
    #}
    server {
    listen 80 default_server;

      location /healthz {
        access_log off;
        return 200 "healthy\n";
      }
    }
    
    upstream kaelgo {
      server kaelgo.ccdior.com:443;
    }
    
    upstream kaelgogo {
      server kaelgogo.ccdior.com:443;
    }
    
    #server {
    #listen 80;
    #       location /test {
    #       return 200 "okok\n";
    #       }
    #}
    server {
    listen 80;
           server_name kaelsite1.ccdior.com;
           location /
           {
                  proxy_pass https://kaelgo;
           }
           #root /var/www/test1;
           #index index.html;
    }
    server {
    listen 80;
           server_name kaelsite2.ccdior.com;
           location /
           {
                  proxy_pass https://kaelgogo;
           }
           #root /var/www/test2;
           #index index.html;
    }
