apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: gcr.io/multi-k8s-ict/nginx-image:latest
        ports:
        - containerPort: 80
#        volumeMounts:
#        - name: config-volume
#          mountPath: /etc/nginx/conf.d/proxy.conf
#          readOnly: true
#      volumes:
#        - name: config-volume
#          configMap:
#            name: special-config
